### PR TITLE
Expose connections through a DataSource

### PR DESCRIPTION
**Pull request by germandt**
Gets easier integration with frameworks which usually wait for this implementation.

### CODE REVIEW

**Comment by dpsoft** [comment]
@germandt LGTM.  WDYT @pablosmedina @aleholman?

**Comment by pablosmedina** [comment]
It's ok for me too. My only concern is just about the naming. Since the project is called galera-java-client, renaming the GaleraClient class to GaleraDatasource can be a little bit confusing (at least for me). I would think of it as a client that implements the Datasource interface. What do you think?

**Comment by germandt** [comment]
Perfect, changes made!

**Comment by dpsoft** [comment]
Done!!!

**Pull request merged**
